// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: EPL

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_leagueScreen
void ui_leagueScreen_screen_init(void);
lv_obj_t * ui_leagueScreen;
lv_obj_t * ui_headerPanel;
lv_obj_t * ui_leagueName;
lv_obj_t * ui_playedTitle;
lv_obj_t * ui_wonTitle;
lv_obj_t * ui_drawTitle;
lv_obj_t * ui_lostTitle;
lv_obj_t * ui_pointsTitle;
lv_obj_t * ui_scoredTitle;
lv_obj_t * ui_concededTitle;
lv_obj_t * ui_differenceTitle;
lv_obj_t * ui_tableList;
lv_obj_t * ui_teamPanel;
lv_obj_t * ui_pos;
lv_obj_t * ui_name;
lv_obj_t * ui_played;
lv_obj_t * ui_won;
lv_obj_t * ui_draw;
lv_obj_t * ui_lost;
lv_obj_t * ui_points;
lv_obj_t * ui_scored;
lv_obj_t * ui_conceded;
lv_obj_t * ui_difference;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
// #if LV_COLOR_DEPTH != 16
//     #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
// #endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_leagueScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_leagueScreen);
}
