// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: EPL

#ifndef _EPL_UI_H
#define _EPL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_leagueScreen
void ui_leagueScreen_screen_init(void);
extern lv_obj_t * ui_leagueScreen;
extern lv_obj_t * ui_headerPanel;
extern lv_obj_t * ui_leagueName;
extern lv_obj_t * ui_playedTitle;
extern lv_obj_t * ui_wonTitle;
extern lv_obj_t * ui_drawTitle;
extern lv_obj_t * ui_lostTitle;
extern lv_obj_t * ui_pointsTitle;
extern lv_obj_t * ui_scoredTitle;
extern lv_obj_t * ui_concededTitle;
extern lv_obj_t * ui_differenceTitle;
extern lv_obj_t * ui_tableList;
extern lv_obj_t * ui_teamPanel;
extern lv_obj_t * ui_pos;
extern lv_obj_t * ui_name;
extern lv_obj_t * ui_played;
extern lv_obj_t * ui_won;
extern lv_obj_t * ui_draw;
extern lv_obj_t * ui_lost;
extern lv_obj_t * ui_points;
extern lv_obj_t * ui_scored;
extern lv_obj_t * ui_conceded;
extern lv_obj_t * ui_difference;
extern lv_obj_t * ui____initial_actions0;





LV_FONT_DECLARE(ui_font_Font1);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
